<?php

$paymentTitle = $block->getMethod()->getConfigData('title', $block->getInfo()->getOrder()->getStoreId());
?>
<div class="order-payment-method-name"><?= $block->escapeHtml($paymentTitle) ?></div>
<table class="data-table admin__table-secondary">
    <tr>
        <th><?= $block->escapeHtml(__('Used Method')) ?>:</th>
        <td><?= $block->escapeHtml($block->getUsedPaymentMethod()) ?></td>
    </tr>
    <tr>
        <th><?= $block->escapeHtml(__('Payment Id')) ?>:</th>
        <td><?= $block->escapeHtml($block->getPaymentId()) ?></td>
    </tr>	
</table>
